---
name: DAS CLI Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Dockerfile
        run: docker build -t das-cli:latest .

      - name: Build das-cli binary
        run: docker run --rm -v "$(pwd)/dist/":/tmp/das-cli/dist das-cli:latest

      - name: Upload das-cli artifact
        uses: actions/upload-artifact@v4
        with:
          name: das-cli
          path: dist/*

  tag:
    needs: build
    if: github.ref == 'refs/heads/master'
    uses: singnet/das-scripts-pipeline/.github/workflows/action.yml@master
    with:
      version: ${{ github.event.inputs.version }}
      version-strategy: bump-version-from-variable-value
      job-image-namespace: trueagi
      job-image-version-semver: semantic-versioning
      main-branch: master
      version-tag-regex-pattern: /^v\d+\.\d+\.\d+$/
      version-require-confirmation: "true"
    secrets: inherit
